import { GoogleGenerativeAI } from "@google/generative-ai";
import { NextResponse } from "next/server";
import { PROFILE_NODE, STATIC_NODES } from "../../components/brain/NeuralData";

// Fix 504 Timeout by using Edge Runtime (25s+ limit)
export const runtime = 'edge';

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || "");

export async function POST(req: Request) {
    try {
        const { currentHero, fullContext } = await req.json();

        // 1. Gather all data
        const resumeData = JSON.stringify({
            profile: PROFILE_NODE,
            projects: STATIC_NODES
        }, null, 2);
        
        const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });
        
        const prompt = `
        ROLE: You are a Senior Executive Recruiter and Resume Strategist (The Scribe Agent). Your goal is to generate a custom, high-impact resume summary for a Tech Lead.
        
        CONTEXT:
        The visitor landed on a unique website generated by AI based on this live context:
        - CURRENT FOCUS (Hook): "${currentHero.title || "General Integrity"}"
        - RELEVANT PROJECT: "${currentHero.relevant_project}"
        - LIVE NEWS SYNOPSIS: "${fullContext.items?.[0]?.articleSummary || "No live news available."}"
        
        MASTER DATA: ${resumeData}

        TASK: 
        Generate a complete resume document in Markdown format.
        1. Create a top "Executive Summary" that directly addresses the "LIVE FOCUS" topic.
        2. Re-organize the experience highlights to place the MOST relevant projects (e.g., TRACE if the context is Policy/Risk) at the top.
        3. Ensure the language uses C-Suite terminology (ROI, Governance, Frictionless, Scalability).
        
        OUTPUT: Return ONLY the raw markdown text for the document.
        `;

        const result = await model.generateContent(prompt);
        const markdown = result.response.text();
        
        // Final Document Assembly
        const datetime = new Date().toLocaleTimeString('en-US', { timeZoneName: 'short', year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' });
        const finalDocument = `# CONTEXT-AWARE EXECUTIVE RESUME\n\n**Generated:** ${datetime}\n\n---\n\n${markdown}`;

        // Create contextual filename
        const focus = currentHero.title ? currentHero.title.replace(/[^a-zA-Z0-9]/g, '_').substring(0, 25) : "Resume";
        const filename = `JWM_Resume_Contextual_${focus}_${new Date().toISOString().substring(0, 10)}.md`;

        return new NextResponse(finalDocument, {
            status: 200,
            headers: {
                'Content-Type': 'text/markdown',
                'Content-Disposition': `attachment; filename="${filename}"`,
            },
        });
    } catch (error) {
        console.error("Scribe Agent Error:", error);
        return new NextResponse("Error generating resume. Please try again later.", { status: 500 });
    }
}
